language: node_js
node_js:
  - "node" # Latest node version
  - "10"
  - "8"

cache: yarn

install:
  - yarn
  - yarn global add codecov

script:
  - yarn test --coverage
  - codecov

notifications:
  email: false
